version: '3.7'
services:
  app:
    build: ./app
    container_name: app
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./app:/app
    depends_on:
      - prisma
  prisma:
    build: ./db-orm
    container_name: prisma
    restart: always
    ports:
      - "2083:3000"
    volumes:
      - ./db-orm:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/postgres?schema=public
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data