services:
  ref-app:
    image: refapp-lite:2.0
    container_name: ref-app
    restart: always
    ports:
      - "80:8080"
    environment:
      # your hostname
      - PUBLIC_HOST=https://ref.paragonusedcars.com
    volumes:
      - ./cert/app:/usr/src/app/cert
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"
    depends_on:
      - ref-orm
    networks:
      - ref-network
  ref-orm:
    image: reform-lite:2.0
    container_name: ref-orm
    restart: always
    ports:
      - "2083:3000"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"
    environment:
      # set your database connection
      
      # APP: production,dev for use ssl on port 3000
      - APP=production
    volumes:
      - ./cert/orm:/usr/src/app/cert
    networks:
      - ref-network

networks:
  ref-network:
    driver: bridge
